phi1_phi2:
	g++ phi1_phi2.cpp -o ../bin/phi1_phi2

int:
	g++ int.cpp -o ../bin/int

b1_b2:
	g++ b1_b2.cpp -o ../bin/b1_b2

u:
	g++ u.cpp -o ../bin/u

matr:
	g++ matr.cpp -o ../bin/matr -llapack -lblas  -lm
